name: Build Repo Listing

on:
  repository_dispatch:
    types: [build-listing]
  workflow_dispatch:
  push:
    branches: main
    paths: source.json

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  listPublishDirectory: template/Website
  pathToTemplate: template
  pathToCi: template/ci

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # check out this repo
      
      - name: Setup Pages
        uses: actions/configure-pages@v3
        
      - name: Setup Pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Build Repository
        uses: gomorroth/vpm-build-repository@v2
        with:
          input: "source.json"
          output: "index.json"
          repo-token: ${{ github.token }}

      - name: Build Pages
        run: |
          cp index.json website/public/index.json
          cd website
          pnpm i --frozen-lockfile
          pnpm build
        
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: website/out
        
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
