name: Build Repo Listing

on:
  repository_dispatch:
    types: [build-listing]
  workflow_dispatch:
  push:
    branches: main
    paths: source.json

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  listPublishDirectory: template/Website
  pathToTemplate: template
  pathToCi: template/ci

jobs:
  build-listing:
    name: build-listing
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # check out this repo

      - uses: gomorroth/vpm-build-repository@v2
        with:
          source: "source.json"
          output: "index.json"
          repo-token: ${{ github.token }}

      - run: |
          cat index.json 

      - uses: pnpm/action-setup@v3
        with:
          version: 8
      
      - run: |
          cp index.json website/public/index.json
          cd website
          pnpm i --frozen-lockfile
          pnpm build

        

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "website/out"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
